### ISSUE TITLE
Sugestão: utilizar column-gap para espaçamento entre os itens

### ISSUE THREAD

**Issue by marllonfrizzo** [hyrycena/repositorioPDi#4]
https://github.com/hyrycena/repositorioPDi/blob/6884ae7a0cf7622d667aa1ab900b2c76a7a6ff5f/brasileirao%20serie%20sei%20la/index.html#L197

Ao invés de utilizar espaços em branco para implementar o espaçamento entre as colunas, uma forma mais eficiente é utilizar o [column-gap](https://developer.mozilla.org/en-US/docs/Web/CSS/column-gap)

```html
...
<div class="column-gap"><i class="fa-solid fa-circle-check"></i>Vitórias</div>
<div class="column-gap"><i class="fa-solid fa-circle-minus"></i>Empates</div>
<div class="column-gap"><i class="fa-solid fa-circle-xmark"></i>Derrota</div>
...
```

```css
.column-gap {
  display: flex;
  flex-direction: row;
  column-gap: 4px;
  align-items: center;
}
```

Resultado
![image](https://github.com/user-attachments/assets/b3460a53-12a6-43f3-80bd-3526fd5c7b21)
